POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
"title": "High-Profile Company Data Breaches 2023",
"author": "Jessica Farrelly",
"url": "https://www.electric.ai/blog/recent-big-company-data-breaches",
"likes": 1
}
